# -*- coding: utf-8 -*-
"""q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W0U5m0Mkz4ZyltCehoIZxFmP8xe87jUQ
"""

uppercase ={'A':0, 'B':1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6, 'H':7, 'I':8,
         'J':9, 'K':10, 'L':11, 'M':12, 'N':13, 'O':14, 'P':15, 'Q':16,
         'R':17, 'S':18,  'T':19, 'U':20, 'V':21, 'W':22, 'X':23, 'Y':24,
         'Z':25}

inv_uppercase = {0:'A', 1:'B', 2:'C', 3:'D', 4:'E', 5:'F', 6:'G', 7:'H',
                 8:'I', 9:'J', 10:'K', 11:'L', 12:'M', 13:'N', 14:'O', 15:'P',
                 16:'Q', 17:'R', 18:'S', 19:'T', 20:'U', 21:'V', 22:'W', 23:'X',
                 24:'Y', 25:'Z'}

                
ciphertext = "JYPR LTAXTNM, SOGELBCONN IL TNY ZER TU VGIELOUCCX, EXEPY LABUH"
subciphertext = "EXEPY LABUH"
subplaintext = "ERKAY SAVAS"

diff= []
for i in range(len(subciphertext)):
  if subciphertext[i].isalpha():
    cipher_num = uppercase[subciphertext[i]]
    plain_num = uppercase[subplaintext[i]]
    diff.append((cipher_num - plain_num)%26)

print(diff)

keyVector = [6,20,15,0,19,0]
key = ""
for i in keyVector:
  key += inv_uppercase[i]
print("Key is:", key)

plaintext = ""
count = 0
for char in ciphertext:
  if char.isalpha():
    plaintext += inv_uppercase[(uppercase[char] - keyVector[count % 6]) % 26]
    count += 1
  else:
    plaintext += char
  
print("Plaintext is:", plaintext)