# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FW67BHOPy1_HKtk6h7b12TSdwOAqFw1J
"""

!pip install pyprimes

!pip install pycryptodome

import math
import random as rnd
import sympy
import requests
from RSA_OAEP import RSA_OAEP_Enc, RSA_OAEP_Dec

API_URL = 'http://cryptlygos.pythonanywhere.com'

my_id = 25359   #Change this to your ID

endpoint = '{}/{}/{}'.format(API_URL, "RSA_OAEP", my_id )   
response = requests.get(endpoint) 	
c, N, e = 0,0,0 
if response.ok:	
  res = response.json()
  c, N, e = res['c'], res['N'], res['e']    ##get c, N, e
else: print(response.json())

########
k0 = 8

for pin in range(0, 10000):
  for r in range(2**(k0-1), 2**k0):
    currEncryption = RSA_OAEP_Enc(pin, e, N, r)
    if currEncryption == c:
      print("pin is", pin)
      print("r is", r)
      PIN_ = pin
      break
      
#########
# Client sends PIN_ to server
endpoint = '{}/{}/{}/{}'.format(API_URL, "RSA_OAEP", my_id, PIN_)
response = requests.put(endpoint)
print(response.json())